#服务器端口和项目名称配置
server:
  port: 8081
#数据库配置
spring:
  datasource:
    name: springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://122.114.50.37:3306/block_chain?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: tempPassword@;
#    url: jdbc:mysql://192.168.1.109:3306/block_chain?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: ",04GugcEOSnh"
    url: jdbc:mysql://localhost:3306/block_chain?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: "123456"
    #password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 这里我使用了devtool热部署技术，这样就不需要每次都重启服务！！-->
  debug: true
  spring:
    devtools:
      restart:
        enabled: true  #设置开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  #配置Mapper.xml映射文件
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/,classpath:/templates/,file:d:/blockimg/
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
